[env:JC4827W543]

platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_build.partitions = huge_app.csv
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.arduino.memory_type = qio_opi

board_upload.flash_size = 4MB

build_flags =
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DLV_CONF_INCLUDE_SIMPLE
    -I include

lib_deps =
    https://github.com/moononournation/Arduino_GFX
    lvgl/lvgl@8.4.0
    bblanchon/ArduinoJson@^7.4.2